{application,rpc_demo,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{rpc_demo_app,[]}},
              {env,[]},
              {modules,[ernie_sequence,rpc_demo,rpc_demo_app,rpc_demo_sup,
                        sequence,spooky_sequence,webmachine_sequence]}]}.
